import std/[options, strutils]
import ../commitparser
import ../config
import ../result

func isAutoGenerated*(raw: string): bool =
  raw.startsWith("fixup! ") or raw.startsWith("squash! ") or raw.startsWith("amend! ")

proc cmdCheckCommitMsg*(repoRoot: string, msgFilePath: string) =
  let raw = readFile(msgFilePath)
  if isAutoGenerated(raw):
    return
  let parseResult = parseCommitMessage(raw)
  if isFailure(parseResult):
    stderr.writeLine("nimver: invalid commit message: " & parseResult.error)
    quit(1)

  let cfg = loadUserConfig(repoRoot)
  let maybeLevel = validateAndLookup(cfg, parseResult.value)
  if isNone(maybeLevel):
    stderr.writeLine(
      "nimver: unknown commit type '" & parseResult.value.commitType & "'"
    )
    quit(1)
