import std/[options, strutils, sugar]
import ../sysio
import ../commitparser
import ../config
import ../result

func isAutoGenerated*(raw: string): bool =
  raw.startsWith("fixup! ") or raw.startsWith("squash! ") or raw.startsWith("amend! ")

proc cmdCheckCommitMsg*(repoRoot: string, msgFilePath: string): Result[Unit] =
  let raw = readFileContents(msgFilePath)
  if isAutoGenerated(raw):
    return Success()
  parseCommitMessage(raw).flatMap(
    (parsed: ParsedCommit) =>
      loadUserConfig(repoRoot).validateAndLookup(parsed).successOr(
        "nimver: unknown commit type '" & parsed.commitType & "'"
      )
  )
